# Generated by Django 4.1 on 2022-09-02 06:49

from django.db import migrations, models
import sportpredictor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=sportpredictor.models.target_name_creator, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Not Associated', max_length=50)),
                ('Location', models.CharField(default='Not Associated', max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('height', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=3)),
                ('armspan', models.IntegerField(max_length=3)),
                ('foot_length', models.IntegerField(max_length=3)),
                ('one_hand_length', models.IntegerField(max_length=3)),
                ('shoulder_size', models.IntegerField(max_length=3)),
            ],
        ),
    ]
