# Generated by Django 4.1 on 2022-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='armspan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='foot_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='one_hand_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='shoulder_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
