# Generated by Django 4.1 on 2022-09-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0003_alter_target_armspan_alter_target_foot_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='armspan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='foot_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='one_hand_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='shoulder_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
