# Generated by Django 4.1 on 2022-09-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0004_alter_target_armspan_alter_target_foot_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50)),
                ('height', models.PositiveIntegerField(null=True)),
                ('weight', models.PositiveIntegerField(null=True)),
                ('armspan', models.PositiveIntegerField(null=True)),
                ('foot_length', models.PositiveIntegerField(null=True)),
                ('one_hand_length', models.PositiveIntegerField(null=True)),
                ('shoulder_size', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='armspan',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='foot_length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='one_hand_length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='shoulder_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
