# Generated by Django 4.1 on 2022-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0005_sport_alter_target_armspan_alter_target_foot_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='foot_length',
            new_name='Aerobic',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='height',
            new_name='Lactic_anaerobic',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='one_hand_length',
            new_name='anaerobic',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='weight',
            new_name='back_flexibility',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='sport',
            name='fa_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='sport',
            name='fat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='finger_ratio',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='foot_length_to_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='height_to_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='one_hand_length_to_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='shoulder_flexibility',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='back_flexibility',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='back_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='fat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='finger_ratio_2_4',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='shoulder_flexibility',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='super_test_1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='super_test_2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='super_test_3',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
