# Generated by Django 4.1 on 2022-09-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0007_target_neck_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='target',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
