# Generated by Django 4.1 on 2022-09-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0009_alter_target_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='medians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=40)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
