# Generated by Django 4.1 on 2022-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0012_rename_back_size_target_neck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='hip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
