# Generated by Django 4.1 on 2022-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportpredictor', '0013_target_hip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='finger_ratio_2_4',
        ),
        migrations.AddField(
            model_name='target',
            name='finger_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='finger_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='armspan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='back_flexibility',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='foot_length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='hip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='neck',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='one_hand_length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='shoulder_flexibility',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='shoulder_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='waist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
